kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user_role-binding
  namespace: mosip
subjects:
- kind: User
  name: user1
  apiGroup: ""
roleRef:
  kind: Role
  name: user_role
  apiGroup: ""