apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  #annotations:
  #  pv.beta.kubernetes.io/gid: "2000"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"