kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Values.job.rolename }}-{{ .Release.Namespace }}"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
