CREATE SCHEMA "MOCKAUTHDATA";

CREATE TABLE "MOCKAUTHDATA"."MOCK_IDENTITY" ("INDIVIDUAL_ID" VARCHAR(36) NOT NULL, "IDENTITY_JSON" VARCHAR(2048) NOT NULL);

ALTER TABLE "MOCKAUTHDATA"."MOCK_IDENTITY" ADD CONSTRAINT "PK_MOCK_ID_CODE" PRIMARY KEY ("INDIVIDUAL_ID");